/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <stdint.h>

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_CFGR_OFFSET 0x08UL

#define RCC_CFGR_REG (RCC_BASE_ADDR + RCC_CFGR_OFFSET)

#define RCC_AHB1_EN_OFFSET 0x30UL

#define RCC_AHB1_EN_REG (RCC_BASE_ADDR + RCC_AHB1_EN_OFFSET)

#define GPIOA_BASE_ADDR 0x40020000UL
#define GPIOA_MODE_OFFSET 0x00UL
#define GPIOA_MODE_REG  (GPIOA_BASE_ADDR + GPIOA_MODE_OFFSET)

int main(void)
{
	uint32_t *pRccCfgrReg = (uint32_t *) RCC_CFGR_REG;
	uint32_t *pRccAhb1EnReg = (uint32_t *) RCC_AHB1_EN_REG;

	// Configure RCC_CFGR register by select HSI clock to power MCO1
	*pRccCfgrReg &= ~(0x3 << 21);  // clear bit pos. 21 and 22

	//enable clock for GPIOA
	*pRccAhb1EnReg |= (1<<0); // set bit pos. 1
	// set mode for PA8 to AF
	*pGpioModeReg &= ~(3<<16); // clear 16 and 17
	*pGpioModeReg |= (1<<17);  // set 17
	// set PA8's AF to MC01
	uint32_t *pGpioAfHighReg = (uint32_t *)(GPIOA_BASE_ADDR + 0x24UL)
	*pGpioAfHighReg  &=  ~(0xf	 << 0);
	for(;;);
}
