/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <stdint.h>
#define RCC_BASE_ADDR 0x40023800UL
#define RCC_APB2_EN_REG_OFFSET 0x44UL
#define RCC_APB2_EN_REG (RCC_BASE_ADDR + RCC_APB2_EN_REG_OFFSET)
#define ADC_BASE_ADDR 0x40012000UL
#define ADC_CR1_REG_OFFSET  0x04UL
#define ADC_CR1_ADDR ((ADC_BASE_ADDR) + (ADC_CR1_REG_OFFSET))
int main(void)
{
	uint32_t *pApb2ClkEnReg = (uint32_t *) RCC_APB2_EN_REG;
	uint32_t *pAdcCr1Reg = (uint32_t *)ADC_CR1_ADDR;
	*pApb2ClkEnReg |= (7 << 8); // enable ADC1, ADC2, ADC3
	*pAdcCr1Reg |= (uint32_t) (1<<8); // enable scan function
	for(;;);
}
